---
title: " Audit Experiment " 
output:
  rmarkdown::html_vignette:
              bibliography: bib.bib
vignette: |
  %\VignetteIndexEntry{Audit Experiment}
  %\VignetteEngine{knitr::rmarkdown} 
  %\VignetteEncoding{UTF-8}
---
              
```{r, include=FALSE, eval=TRUE}
options("keep.source"=TRUE,
        knitr.duplicate.label = "allow" )
library(knitr)
library(ggplot2)
library(DesignLibrary)
```
              
<div class="btn-group">
  <a class="btn btn-primary" href="http://declaredesign.org/articles/audit_experiment.R">
     <i class="fa fa-code" title = "Download code for design" fa-2x></i> Download code
  </a>
  &nbsp;
  <a class="btn btn-primary" href="http://declaredesign.org/articles/audit_experiment_designer.RDS">
     <i class="fa fa-clipboard" title = "Download template for design" fa-2x></i> Download template
  </a> 
<!--
   <a class="btn btn-primary" href="http://shiny.declaredesign.org/inspector/?topic=audit_experiment">
    <i class="fa fa-area-chart" title = "Go to the design inspector" fa-2x></i> Inspect design
  </a>
--> 
</div>
            
  

 Description here

```{r, code = designer_default_args_text(audit_experiment_designer)}
```

  
```{r, code = audit_experiment_designer(code = TRUE)}
```
```{r,eval = FALSE}
diagnosis <- diagnose_design(audit_experiment_design, sims = 1000, bootstrap = FALSE)
```
```{r audit_experiment_diagnosis,echo = FALSE}
 diagnosis <- get_or_run_diagnosis(audit_experiment_design, sims = 1000, bootstrap = FALSE)
 knitr::kable(reshape_diagnosis(diagnosis, digits = 2), digits = 2)
```

```{r audit_experiment_shiny_diagnosis,include = FALSE}
 get_or_run_shiny_diagnosis(audit_experiment_designer(), 1000, bootstrap = FALSE)
```
                     
 
 <!-- CUSTOM CSS; PLEASE DO NOT DELETE -->.
 ```{css, echo = FALSE}
 table{
   border: 1px solid black;
   table-layout: fixed;
   max-width: 800px;
   width: 100%;
   style="word-break:break-all;"
 }                
 
 th, td {
   border: 1px solid black;
   max-width: 80px;
   width: 100%;
   font-size: 12px;
   
   /* CSS 3 */
     white-space: -o-pre-wrap;
   word-wrap: break-word;
   white-space: pre-wrap;
   white-space: -moz-pre-wrap;
   white-space: -pre-wrap;
 }
 
 ```

