---
title: " bla " 
output:
  rmarkdown::html_vignette:
              css: !expr system.file("css", "vignette.css", package = "DesignLibrary")
              bibliography: bib.bib
vignette: |
  %\VignetteIndexEntry{bla}
  %\VignetteEngine{knitr::rmarkdown} 
  %\VignetteEncoding{UTF-8}
---
              
```{r, include=FALSE, eval=TRUE}
options("keep.source"=TRUE,
        knitr.duplicate.label = "allow" )
library(knitr)
library(ggplot2)
library(DesignLibrary)
```
              
<div class="btn-group">
  <a class="btn btn-primary" href="http://declaredesign.org/articles/test.R">
     <i class="fa fa-code" title = "Download code for design" fa-2x></i> Download code
  </a>
  &nbsp;
  <a class="btn btn-primary" href="http://declaredesign.org/articles/test_designer.RDS">
     <i class="fa fa-clipboard" title = "Download template for design" fa-2x></i> Download template
  </a> 
<!--
   <a class="btn btn-primary" href="http://shiny.declaredesign.org/inspector/?topic=test">
    <i class="fa fa-area-chart" title = "Go to the design inspector" fa-2x></i> Inspect design
  </a>
--> 
</div>
            
  

bla

```{r, code = designer_default_args_text(test_designer)}
```

  
```{r, code = test_designer(code = TRUE)}
```
```{r,eval = FALSE}
diagnosis <- diagnose_design(test_design, sims = 1000, bootstrap = FALSE)
```
```{r test_diagnosis,echo = FALSE}
 diagnosis <- get_or_run_diagnosis(test_design, sims = 1000, bootstrap = FALSE)
 knitr::kable(reshape_diagnosis(diagnosis, digits = 2), digits = 2)
```

```{r test_shiny_diagnosis,include = FALSE}
 get_or_run_shiny_diagnosis(test_designer(), 1000, bootstrap = FALSE)
```
                     

bla
