#' Simple two arm design
#' 
#' A two arm design generated by simple_two_arm_designer
#' 
#' @docType data 
#' @keywords datasets 
#' @name simple_two_arm_design
#' @usage summary(simple_two_arm_design)
#' @format A design

'simple_two_arm_design'